CREATE DATABASE loja;

USE loja;

CREATE TABLE clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL
);

CREATE TABLE pedidos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cliente_id INT,
  descricao VARCHAR(100) NOT NULL,
  valor DOUBLE NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);
