name: bancoapi
description: Exemplo de uso de API
version: 1.0.0

environment:
  sdk: ^3.8.1


dependencies:
  mysql_client: ^0.0.27 #mantido para acessar o mysql
  shelf: ^1.4.1 #Framework HTTP para Dart
  shelf_router: ^1.1.0 #Para roteamento das URL's
  #shelf_static: ^1.1.2 #Opcional: para servir arquivos estaticos, se aplicavel
  shelf_io: ^1.0.0 

